#7 세션 기반 로그인 API
f-lab-edu/sendzy pull request #14
Opened 2024-12-11 16:50 UTC by donggi-lee-bit

세션 기반 로그인 API 추가하였습니다.

- Session은 요청 처리 중 세션이 필요한 경우에만 생성하도록 설정 (`SessionCreationPolicy.IF_REQUIRED`)
- `Session Fixation` 공격을 방지하기 위해 인증이 정상적일 때마다 새로운 세션을 발급(`sessionFixation(SessionManagementConfigurer.SessionFixationConfigurer::newSession)`)
- 악성 스크립트로 쿠키를 탈취하는 걸 방지하기 위해 `HttpOnly` 설정
- 쿠키는 데이터가 암호화된 상태에서만 통신하기 위해 `cookie secure` 설정

2024-12-12 14:17 UTC, f-lab-maverick requested changes
Spring Security를 잘 구현해주셨습니다.
작성해주신 여러가지 설정 파일들이 있는데요, 시큐리티에 설정하면 시큐리티가 알아서 호출해주기때문에 로그인시 어떤 동작이 벌어지는지 알기 어려운 경우가 많습니다.
아래와 같이 인증의 성공/실패 과정을 작성해서 코멘트로 남겨주세요. 고생하셨습니다~


로그인 성공 시나리오
1. 클라이언트가 ID/Password를 전송
2. 로그인요청이 서버에 도착
3. authenticationManager가 해당 요청을 토큰형태로 만들어 xxx에 전달
...

.. 클라이언트는 response header에 있는 세션키를 획득

2024-12-12 14:17 UTC, f-lab-maverick commented on src/main/java/com/donggi/sendzy/common/config/SecurityConfig.java
> +    }
직접 메서드 호출을 진행하는것 보다, 파라미터를 통해 주입받도록 만드는 것이 명시적이고 테스트도 편리해집니다. 

```java
public AuthenticationManager authenticationManager(UserDetailsService userDetailsService, PasswordEncoder passwordEncoder) {
    final var authenticationProvider = new DaoAuthenticationProvider();
    authenticationProvider.setUserDetailsService(userDetailsService);
    authenticationProvider.setPasswordEncoder(passwordEncoder);
    return new ProviderManager(authenticationProvider);
}
```

2024-12-12 14:17 UTC, f-lab-maverick commented on src/main/java/com/donggi/sendzy/common/config/SecurityConfig.java
> +    }
UserDetailsService를 익명클래스로 만든 이유가 있을까요?

2024-12-12 14:17 UTC, f-lab-maverick commented on src/main/java/com/donggi/sendzy/member/application/AuthService.java
> +    public void authenticate(final LoginRequest loginRequest, final HttpSession session) {
session변수를 사용하지 않고 있습니다. 해당 파라미터를 추가한 이유가 없다면 제거해주세요~

2024-12-12 14:17 UTC, f-lab-maverick commented on src/main/java/com/donggi/sendzy/member/application/AuthService.java
> +            SecurityContextHolder.getContext().setAuthentication(authentication);
이 코드에서는 직접적으로 User의 ID / Password를 비교하는 로직이 없음에도 정상적으로 로그인 체크가 동작합니다. 어떤 과정을 통해 id / password를 직접 비교하는 로직을 작성하지 않았음에도 동작할까요?

2024-12-12 14:17 UTC, f-lab-maverick commented on src/main/java/com/donggi/sendzy/member/domain/MemberService.java
> +    }
메서드 네이밍인 `findBy~~~`는 무언가를 검색한다는 뜻입니다.
즉 있으면 리턴 / 없을수도 있음을 의미하는 네이밍으로, 없을경우 예외를 던진다는걸 예측하기 어렵습니다.
없으면 예외를 던질경우 일반적으로 `getBy~~~` 또는 `findBy~~OrThrow`  형식으로 네이밍을 지켜주어야 가독성과 코드 동작에 대한 예측을 더 좋게 만들 수 있습니다. 네이밍은 호출자가 메서드 동작을 명확히 이해할 수 있도록 의도를 드러내는 방식으로 설정하는 것이 중요합니다.

2024-12-12 14:17 UTC, f-lab-maverick commented on src/main/resources/mybatis-config.xml
> +        <setting name="mapUnderscoreToCamelCase" value="true"/>
👍
이 옵션에 대해 설명을 댓글로 적어주세요~

2024-12-12 14:17 UTC, f-lab-maverick commented on src/test/java/com/donggi/sendzy/member/integration/LoginIntegrationTest.java
테스트코드도 이제 꽤 깔끔하게 잘 작성하시네요 좋습니다~

2024-12-13 06:10 UTC, donggi-lee-bit commented on src/main/resources/mybatis-config.xml
> +        <setting name="mapUnderscoreToCamelCase" value="true"/>
under score로 표기된 데이터베이스 컬럼과 camel case로 표기된 프로퍼티를 자동으로 매핑해주는 옵션입니다. 😄

2024-12-13 06:13 UTC, donggi-lee-bit commented on src/main/java/com/donggi/sendzy/member/domain/MemberService.java
> +    }
메서드 네이밍에 예외가 발생하는 경우를 고려하지 못했습니다 😂 `findByEmailOrThrow()` 로 수정하겠습니다!

2024-12-13 06:52 UTC, donggi-lee-bit commented on src/main/java/com/donggi/sendzy/common/config/SecurityConfig.java
> +    }
UserDetailsService를 Bean으로 등록하는 코드에서 사용자 정보를 조회하고 반환하는 로직만 필요하기 때문에 익명 클래스로 만들어도 충분하다고 판단했습니다.

만약 로직이 더 복잡해지거나 UserDetailsService 구현체가 필요하다면, 별도의 클래스를 정의해서 사용할 수 있을 것 같습니다.

2024-12-15 08:35 UTC, donggi-lee-bit commented on src/main/java/com/donggi/sendzy/member/application/AuthService.java
> +    public void authenticate(final LoginRequest loginRequest, final HttpSession session) {
현재 세션 생성 정책을 `IF_REQUIRED`로 설정하고 있습니다. IF_REQUIRED는 인증이 필요한 요청에서 세션이 없을 경우 세션을 생성하게 되는데요. 말씀하신 것처럼 AuthService.authenticate() 메서드에서 HttpSession을 매개변수로 받지 않아도, Spring Security의 기본 동작으로 인해 인증을 처리하는 객체인 Authentication 객체가 SecurityContext에 저장됩니다.

하지만 로그인을 처리하는 Controller 메서드에서는 HttpSession을 매개변수로 받아야 Spring Security가 인증이 필요한 요청임을 확인하고, 인증 프로세스가 동작하고 세션이 생성됩니다.

이렇게 되면 지금 리뷰해주신 내용과 같이 Controller 메서드에서는 Session 변수를 받아서 사용하지 않게 되는데, 이런 경우에는 어떻게 처리하는게 좋을까요? 주석으로 Session 변수를 받아서 사용하지 않는 이유에 대해 작성하면 될까요?

2024-12-15 09:02 UTC, donggi-lee-bit commented on src/main/java/com/donggi/sendzy/member/application/AuthService.java
> +            SecurityContextHolder.getContext().setAuthentication(authentication);
id/pw를 직접 비교하는 로직을 작성하지 않아도 로그인 체크가 동작하는 이유는 Spring Security의 인증 메커니즘에 의해 처리되기 때문입니다.

1. 사용자가 입력한 id/pw를 Authentication 객체로 만들어 AuthenticationManager에게 전달합니다.
2. AuthenticationManager는 DaoAuthenticationProvider에게 인증 작업을 위임하고, 주입 받은 UserDetailsService와 PasswordEncoder를 사용하여 사용자 정보를 조회하고, 비밀번호 일치 여부를 확인합니다.

2024-12-15 09:22 UTC, donggi-lee-bit commented
> Spring Security를 잘 구현해주셨습니다. 작성해주신 여러가지 설정 파일들이 있는데요, 시큐리티에 설정하면 시큐리티가 알아서 호출해주기때문에 로그인시 어떤 동작이 벌어지는지 알기 어려운 경우가 많습니다. 아래와 같이 인증의 성공/실패 과정을 작성해서 코멘트로 남겨주세요.

Spring Security 설정을 통해 로그인이 동작하는 방식은 다음과 같습니다. @f-lab-maverick 

**로그인 성공 시나리오**
1. 클라이언트가 id/pw를 포함하여 로그인 요청을 전송
2. 인증 토큰 생성
    - 로그인 요청을 `UsernamePasswordAuthenticationFilter`가 가로챔
    - `UsernamePasswordAuthenticationToken` 객체 생성
3. 인증 요청 처리
    - 인증을 담당하는 `AuthenticationManager` 호출
    - AuthenticationManager는 UsernamePasswordAuthenticationToken을 처리하기 위한 `AuthenticationProvider`를 호출
4. 사용자 조회, 비밀번호 검증
    - AuthenticationProvider가 주입 받은 UserDetailsService를 호출하여 사용자 정보를 조회하고, 비밀번호가 일치한지 검증
5. 인증 결과 저장
    - (UserDetailsService에서 사용자 정보가 조회되고, 비밀번호가 일치할 경우) `Authentication` 객체를 `SecurityContext`에 저장
6. 세션 반환
    - HTTP Response Header의 Set-Cookie에 세션 ID를 포함하여 반환
    
**로그인 실패 시나리오**
.
.
.
(요청, 토큰 생성 등 앞선 인증 과정은 동일)
.
.
.

4. 사용자 조회, 비밀번호 검증
    - UserDetailsService에서 입력한 ID로 사용자가 조회되지 않을 경우 예외 반환
    - (입력한 ID로 사용자가 조회된 경우) 비밀번호가 일치하지 않을 경우 예외 반환

2024-12-15 23:04 UTC, f-lab-maverick commented on src/main/java/com/donggi/sendzy/member/application/AuthService.java
> +    public void authenticate(final LoginRequest loginRequest, final HttpSession session) {
네, 기본값으로는 모든 요청에 대해 세션을 생성하기때문에 세션 파라미터를 받는 이유를 컨트롤러 메서드에 주석으로 설명을 달아주는게 좋겠네요~

2024-12-15 23:06 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다

2024-12-15 23:12 UTC, merged